name: Documentation and Helm chart

on:
  push:
    branches:
      - master

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: ./.github/actions/mkdocs
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

  chart:
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Setup
        shell: bash
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-rc.2
        env:
          CR_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
